timeout: 1
region: us-east-1
s3bucket: all-reports
s3keyData: measurements
s3KeyReport: report.html
services:
  - name: foo
    url: https://foo.example.com
  - name: bar
    url: https://bar.example.com
